DEBUG = True
SECRET_KEY = 'TODO'

DATABASE = {
    'name': 'cafebabel.db',
    'engine': 'peewee.SqliteDatabase',
}

SECURITY_PASSWORD_SALT = 'and pepper'
SECURITY_CONFIRMABLE = True
SECURITY_REGISTERABLE = True
SECURITY_RECOVERABLE = True
SECURITY_CHANGEABLE = True
SECURITY_EMAIL_SENDER = 'no-reply@cafebabel.com'

SECURITY_FORGOT_PASSWORD_TEMPLATE = 'forgot.html'
SECURITY_CHANGE_PASSWORD_TEMPLATE = 'change.html'
SECURITY_RESET_PASSWORD_TEMPLATE = 'reset.html'
SECURITY_LOGIN_USER_TEMPLATE = 'login.html'
SECURITY_REGISTER_USER_TEMPLATE = 'register.html'
SECURITY_SEND_CONFIRMATION_TEMPLATE = 'confirmation.html'
EXPLAIN_TEMPLATE_LOADING = True
DEBUG_TB_INTERCEPT_REDIRECTS = False
